### ISSUE TITLE
DataSet

### ISSUE THREAD

**Issue by sendream** [DIVA-DIA/LayoutAnalysisEvaluator#1]
Hello, I am a student who is just starting my research on OCR of ancient books, I would like to ask if the dataset of "ICDAR 2019 Historical Document Reading Challenge on Large Structured Chinese Family Records" is still available?

**Comment by lvoegtlin** [comment]
Hei,
I am not an organizer of the competition, but the dataset can be found here: https://tc11.cvc.uab.es/datasets/ICDAR2019HDRC_1
If you would like more information, you would need to contact one of the organizers.

**Comment by sendream** [comment]
> 嘿， 我不是比赛的组织者，但数据集可以在这里找到： https: [//tc11.cvc.uab.es/datasets/ICDAR2019HDRC_1](https://tc11.cvc.uab.es/datasets/ICDAR2019HDRC_1) 如果您想了解更多信息，您需要联系组织者之一。

Thank you for the information and have a nice life!

**Comment by sendream** [comment]
> Hei, I am not an organizer of the competition, but the dataset can be found here: https://tc11.cvc.uab.es/datasets/ICDAR2019HDRC_1 If you would like more information, you would need to contact one of the organizers.

Thank you for the information and have a nice life!
